

trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- script: echo "CodeceptJS demo project"
  


    
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'


- script: npx codeceptjs run --steps
