

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    bat npx selenium-standalone start
    bat npx codeceptjs run --steps
    
